version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodb_data:/data/db
    networks: [app_network]

  tomcat:
    build:
      context: ./students-web
    container_name: tomcat
    ports:
      - "8080:8080"
    depends_on: [mongodb]
    networks: [app_network]

  terminal:
    build:
      context: ./students-terminal
    container_name: terminal
    depends_on: [mongodb]
    stdin_open: true
    tty: true
    networks: [app_network]

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data: