apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-terminal
  labels:
    app: {{ .Release.Name }}-terminal
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-terminal
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-terminal
    spec:
      containers:
        - name: terminal
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          stdin: true
          tty: true
          env:
            - name: MONGO_INITDB_HOST
              value: students-db
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: password
            - name: MONGO_INITDB_DATABASE
              value: students
