apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-terminal
  labels:
    app: {{ .Release.Name }}-terminal
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: {{ .Release.Name }}-terminal
  ports:
    - protocol: TCP
      port: {{ .Values.service.port | default 8080 }}
      targetPort: 8080
