apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.app.name }}-web
  labels:
    app: {{ .Values.global.app.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.global.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.app.name }}
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_INITDB_HOST
              value: students-db
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: password
            - name: MONGO_INITDB_DATABASE
              value: students
