apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.app.name }}-service
  labels:
    run: {{ .Values.global.app.name }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ .Values.global.app.name }}
